### PR TITLE
Added control values support for Language with local authority management. #2

### PR DESCRIPTION
**Pull request by lsitu**
https://github.com/ucsdlib/dams5-cc-pilot/issues/2

### CODE REVIEW

**Comment by lsitu** [comment]
@ucsdlib/developers Please review, comments etc... Thanks.

**Comment by mcritchlow** [comment]
This looks reasonable to me. Part of me wonders if we really need to be persisting the language CV in our repo, but overall I think this looks good 👍 

@remerjohnson - I know you're on the Hydra Linked Authority Interest Group now. I'd be very interested in hearing what other folks are doing for this kinda thing, if you have an opportunity to bring it up.

**Comment by VivianChu** [comment]
👍

**Comment by hweng** [comment]
The same question as @mcritchlow, otherwise it looks :+1: to me.

**Comment by lsitu** [comment]
@ucsdlib/developers Thanks everyone for reviewing. And yes we could improve it with other better approach later.
Could anyone merge it if you are convenient? Thanks

**Review by hweng — APPROVED** [review]

**Comment by remerjohnson** [comment]
@mcritchlow Will do. In the meantime, I've tried to start a discussion in the Hydra #metadata Slack to see how others in the community are doing it.

**Pull request merged**
