### PR TITLE
Add A-Z links to facet view pages. (#33)

### PR DESCRIPTION
**Pull request by hweng**

### CODE REVIEW

**Comment by hweng** [comment]
@ucsdlib/developers Please review, comments etc... Thanks.

**Comment by mcritchlow** [comment]
👍 looks good to me, but will let @lsitu and @VivianChu do the formal review

**Comment by VivianChu** [comment]
👍

**Comment by lsitu** [comment]
@hweng I see lots of changes on Gemfile.lock file but can't find anything committed to Gemfile. Do you make any changes to the Gemfile?

**Comment by hweng** [comment]
@lsitu No, there is no new gem added in this pull request.
Have you pulled the latest version from github master branch and run bundle install and do you get error? I got errors which I have to delete the Gemfile.lock and then run bundle install and it get fixed. That's why the Gemfile.lock is changed.

**Comment by lsitu** [comment]
@hweng It looks like some weird environment but I think it's fine as long as it works. Actually I didn't get any errors with my last [PR](https://github.com/ucsdlib/dams5-cc-pilot/pull/41/commits/e0ebd6ee93c1fd9c7877410def06ad2e6d9ebc51) that is basing on the latest version from github master branch.

**Review by lsitu — APPROVED** [review]
👍

**Comment by hweng** [comment]
Thanks everyone for reviewing and @lsitu for merging.

**Pull request merged**
